server:
  port: 8080

spring:
  application:
    name: mall-server
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.mall: DEBUG
    org.springframework: INFO
